/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <string>


#include "data_pool_accessor.hpp"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1i32_1identifier_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32_identifier = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1i32_1identifier_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (int) ((arg1)->i32_identifier);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1min_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->f_min = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1min_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (float) ((arg1)->f_min);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1max_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->f_max = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1max_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (float) ((arg1)->f_max);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1zero_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->f_zero = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1zero_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (float) ((arg1)->f_zero);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->f_value = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1f_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (float) ((arg1)->f_value);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1str_1description_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->str_description = *arg2;
}


SWIGEXPORT jstring JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1str_1description_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (std::string *) & ((arg1)->str_description);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1str_1unit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->str_unit = *arg2;
}


SWIGEXPORT jstring JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDData_1str_1unit_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  result = (std::string *) & ((arg1)->str_unit);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DataPoolOBDData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolOBDData *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolOBDData *)new DataPoolOBDData();
  *(DataPoolOBDData **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DataPoolOBDData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DataPoolOBDData *arg1 = (DataPoolOBDData *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DataPoolOBDData **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32CatalystState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32CatalystState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32CatalystState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->i32CatalystState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32HeatedCatalystState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32HeatedCatalystState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32HeatedCatalystState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->i32HeatedCatalystState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32EVAPSystemState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32EVAPSystemState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32EVAPSystemState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->i32EVAPSystemState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32SecondaryAirSystemState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32SecondaryAirSystemState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32SecondaryAirSystemState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->i32SecondaryAirSystemState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32OxygenSensorState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32OxygenSensorState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32OxygenSensorState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->i32OxygenSensorState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32OxygenSensorHeaterState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32OxygenSensorHeaterState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1i32OxygenSensorHeaterState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->i32OxygenSensorHeaterState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1I32EGRState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->I32EGRState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDReadynessCode_1I32EGRState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  result = (int) ((arg1)->I32EGRState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DataPoolOBDReadynessCode(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolOBDReadynessCode *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolOBDReadynessCode *)new DataPoolOBDReadynessCode();
  *(DataPoolOBDReadynessCode **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DataPoolOBDReadynessCode(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DataPoolOBDReadynessCode *arg1 = (DataPoolOBDReadynessCode *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1i32FanState_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->i32FanState = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1i32FanState_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  result = (int) ((arg1)->i32FanState);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1bo_1request_1override_1soc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->bo_request_override_soc = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1bo_1request_1override_1soc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  result = (bool) ((arg1)->bo_request_override_soc);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1u32_1request_1override_1soc_1new_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_request_override_soc_new_value = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1u32_1request_1override_1soc_1new_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_request_override_soc_new_value);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1bo_1request_1override_1fan_1state_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->bo_request_override_fan_state = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1bo_1request_1override_1fan_1state_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  result = (bool) ((arg1)->bo_request_override_fan_state);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1u32_1request_1override_1fan_1state_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_request_override_fan_state_value = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolIMAState_1u32_1request_1override_1fan_1state_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_request_override_fan_state_value);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DataPoolIMAState(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolIMAState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolIMAState *)new DataPoolIMAState();
  *(DataPoolIMAState **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DataPoolIMAState(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DataPoolIMAState *arg1 = (DataPoolIMAState *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DataPoolIMAState **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDDTC_1u32_1dtc_1code_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolOBDDTC *arg1 = (DataPoolOBDDTC *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDDTC **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_dtc_code = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolOBDDTC_1u32_1dtc_1code_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolOBDDTC *arg1 = (DataPoolOBDDTC *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolOBDDTC **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_dtc_code);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DataPoolOBDDTC(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolOBDDTC *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolOBDDTC *)new DataPoolOBDDTC();
  *(DataPoolOBDDTC **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DataPoolOBDDTC(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DataPoolOBDDTC *arg1 = (DataPoolOBDDTC *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DataPoolOBDDTC **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1element_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_element = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1element_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_element);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1row_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_row = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1row_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_row);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1col_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_col = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1col_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_col);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1row_1span_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_row_span = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1row_1span_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_row_span);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1col_1span_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->u32_col_span = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolDisplayedElementData_1u32_1col_1span_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  result = (unsigned int) ((arg1)->u32_col_span);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DataPoolDisplayedElementData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolDisplayedElementData *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolDisplayedElementData *)new DataPoolDisplayedElementData();
  *(DataPoolDisplayedElementData **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DataPoolDisplayedElementData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DataPoolDisplayedElementData *arg1 = (DataPoolDisplayedElementData *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DataPoolDisplayedElementData **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1obd_1data_1array_1element(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  DataPoolOBDData result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = DataPoolAccessor::get_obd_data_array_element(arg1);
  *(DataPoolOBDData **)&jresult = new DataPoolOBDData((const DataPoolOBDData &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1obd_1data_1array_1element(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  int arg1 ;
  DataPoolOBDData *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  arg2 = *(DataPoolOBDData **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "DataPoolOBDData const & reference is null");
    return ;
  } 
  DataPoolAccessor::set_obd_data_array_element(arg1,(DataPoolOBDData const &)*arg2);
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1obd_1data_1array_1num_1of_1elements(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_obd_data_array_num_of_elements();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1main_1view_1elements_1of_1interest_1array_1element(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  DataPoolDisplayedElementData result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = DataPoolAccessor::get_main_view_elements_of_interest_array_element(arg1);
  *(DataPoolDisplayedElementData **)&jresult = new DataPoolDisplayedElementData((const DataPoolDisplayedElementData &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1main_1view_1elements_1of_1interest_1array_1element(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  int arg1 ;
  DataPoolDisplayedElementData arg2 ;
  DataPoolDisplayedElementData *argp2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  argp2 = *(DataPoolDisplayedElementData **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null DataPoolDisplayedElementData");
    return ;
  }
  arg2 = *argp2; 
  DataPoolAccessor::set_main_view_elements_of_interest_array_element(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1main_1view_1elements_1of_1interest_1array_1size(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_main_view_elements_of_interest_array_size();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1main_1view_1elements_1of_1interest_1count(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_main_view_elements_of_interest_count();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1main_1view_1elements_1of_1interest_1count(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  DataPoolAccessor::set_main_view_elements_of_interest_count(arg1);
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1main_1view_1num_1of_1cols(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  DataPoolAccessor::set_main_view_num_of_cols(arg1);
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1main_1view_1num_1of_1cols(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_main_view_num_of_cols();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1main_1view_1num_1of_1rows(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  DataPoolAccessor::set_main_view_num_of_rows(arg1);
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1main_1view_1num_1of_1rows(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_main_view_num_of_rows();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1read_1all_1obd_1values(JNIEnv *jenv, jclass jcls) {
  jboolean jresult = 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  result = (bool)DataPoolAccessor::get_read_all_obd_values();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1read_1all_1obd_1values(JNIEnv *jenv, jclass jcls, jboolean jarg1) {
  jint jresult = 0 ;
  bool arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = jarg1 ? true : false; 
  result = (int)DataPoolAccessor::set_read_all_obd_values(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1obd_1readyness_1code(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolOBDReadynessCode result;
  
  (void)jenv;
  (void)jcls;
  result = DataPoolAccessor::get_obd_readyness_code();
  *(DataPoolOBDReadynessCode **)&jresult = new DataPoolOBDReadynessCode((const DataPoolOBDReadynessCode &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1obd_1readyness_1code(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DataPoolOBDReadynessCode arg1 ;
  DataPoolOBDReadynessCode *argp1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(DataPoolOBDReadynessCode **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null DataPoolOBDReadynessCode");
    return ;
  }
  arg1 = *argp1; 
  DataPoolAccessor::set_obd_readyness_code(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1ima_1state(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolIMAState result;
  
  (void)jenv;
  (void)jcls;
  result = DataPoolAccessor::get_ima_state();
  *(DataPoolIMAState **)&jresult = new DataPoolIMAState((const DataPoolIMAState &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1ima_1state(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  DataPoolIMAState arg1 ;
  DataPoolIMAState *argp1 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  argp1 = *(DataPoolIMAState **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null DataPoolIMAState");
    return ;
  }
  arg1 = *argp1; 
  DataPoolAccessor::set_ima_state(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1obd_1dtc_1array_1element(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  DataPoolOBDDTC result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = DataPoolAccessor::get_obd_dtc_array_element(arg1);
  *(DataPoolOBDDTC **)&jresult = new DataPoolOBDDTC((const DataPoolOBDDTC &)result); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1obd_1dtc_1array_1element(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  int arg1 ;
  DataPoolOBDDTC *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  arg2 = *(DataPoolOBDDTC **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "DataPoolOBDDTC const & reference is null");
    return ;
  } 
  DataPoolAccessor::set_obd_dtc_array_element(arg1,(DataPoolOBDDTC const &)*arg2);
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1obd_1dtc_1array_1num_1of_1elements(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_obd_dtc_array_num_of_elements();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_get_1obd_1dtc_1count(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)DataPoolAccessor::get_obd_dtc_count();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_set_1obd_1dtc_1count(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  DataPoolAccessor::set_obd_dtc_count(arg1);
}


#ifdef __cplusplus
}
#endif

