/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <string>


#include "data_pool.hpp"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1identifier_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->identifier = arg2;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1identifier_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (int) ((arg1)->identifier);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1min_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->min = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1min_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (float) ((arg1)->min);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1max_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->max = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1max_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (float) ((arg1)->max);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1zero_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->zero = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1zero_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (float) ((arg1)->zero);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->value = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (float) ((arg1)->value);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1description_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->description = *arg2;
}


SWIGEXPORT jstring JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1description_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (std::string *) & ((arg1)->description);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1unit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  if(!jarg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null string");
    return ;
  }
  const char *arg2_pstr = (const char *)jenv->GetStringUTFChars(jarg2, 0); 
  if (!arg2_pstr) return ;
  std::string arg2_str(arg2_pstr);
  arg2 = &arg2_str;
  jenv->ReleaseStringUTFChars(jarg2, arg2_pstr); 
  if (arg1) (arg1)->unit = *arg2;
}


SWIGEXPORT jstring JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DpoolOBDData_1unit_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  std::string *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DpoolOBDData **)&jarg1; 
  result = (std::string *) & ((arg1)->unit);
  jresult = jenv->NewStringUTF(result->c_str()); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DpoolOBDData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DpoolOBDData *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DpoolOBDData *)new DpoolOBDData();
  *(DpoolOBDData **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DpoolOBDData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DpoolOBDData *arg1 = (DpoolOBDData *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DpoolOBDData **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DPOOL_1OBD_1DATA_1COLLECTION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  DataPoolItems result;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolItems)DPOOL_OBD_DATA_COLLECTION;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DPOOL_1HMI_1MAIN_1VIEL_1ELEMENTS_1OF_1INTEREST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  DataPoolItems result;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolItems)DPOOL_HMI_MAIN_VIEL_ELEMENTS_OF_INTEREST;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_new_1DataPoolAccessor(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolAccessor *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolAccessor *)new DataPoolAccessor();
  *(DataPoolAccessor **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DataPoolAccessor *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DataPoolAccessor *) &DataPoolAccessor::get();
  *(DataPoolAccessor **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1get_1obd_1data_1array_1element(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  int arg2 ;
  DpoolOBDData result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (arg1)->get_obd_data_array_element(arg2);
  *(DpoolOBDData **)&jresult = new DpoolOBDData((const DpoolOBDData &)result); 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1set_1obd_1data_1array_1element(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  jint jresult = 0 ;
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  int arg2 ;
  DpoolOBDData *arg3 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(DpoolOBDData **)&jarg3;
  if (!arg3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "DpoolOBDData const & reference is null");
    return 0;
  } 
  result = (int)(arg1)->set_obd_data_array_element(arg2,(DpoolOBDData const &)*arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1get_1main_1view_1elements_1of_1interest(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  int arg2 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (unsigned int)(arg1)->get_main_view_elements_of_interest(arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1set_1main_1view_1elements_1of_1interest(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3) {
  jint jresult = 0 ;
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  int arg2 ;
  unsigned int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  result = (int)(arg1)->set_main_view_elements_of_interest(arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1get_1read_1all_1obd_1values(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  result = (bool)(arg1)->get_read_all_obd_values();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_DataPoolAccessor_1set_1read_1all_1obd_1values(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  jint jresult = 0 ;
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  bool arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  result = (int)(arg1)->set_read_all_obd_values(arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_texelography_hybridinsight_datapool_data_1poolJNI_delete_1DataPoolAccessor(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DataPoolAccessor *arg1 = (DataPoolAccessor *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DataPoolAccessor **)&jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

