/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.texelography.hybridinsight.datapool;

public class data_poolJNI {
  public final static native void DataPoolOBDData_i32_identifier_set(long jarg1, DataPoolOBDData jarg1_, int jarg2);
  public final static native int DataPoolOBDData_i32_identifier_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native void DataPoolOBDData_f_min_set(long jarg1, DataPoolOBDData jarg1_, float jarg2);
  public final static native float DataPoolOBDData_f_min_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native void DataPoolOBDData_f_max_set(long jarg1, DataPoolOBDData jarg1_, float jarg2);
  public final static native float DataPoolOBDData_f_max_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native void DataPoolOBDData_f_zero_set(long jarg1, DataPoolOBDData jarg1_, float jarg2);
  public final static native float DataPoolOBDData_f_zero_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native void DataPoolOBDData_f_value_set(long jarg1, DataPoolOBDData jarg1_, float jarg2);
  public final static native float DataPoolOBDData_f_value_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native void DataPoolOBDData_str_description_set(long jarg1, DataPoolOBDData jarg1_, String jarg2);
  public final static native String DataPoolOBDData_str_description_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native void DataPoolOBDData_str_unit_set(long jarg1, DataPoolOBDData jarg1_, String jarg2);
  public final static native String DataPoolOBDData_str_unit_get(long jarg1, DataPoolOBDData jarg1_);
  public final static native long new_DataPoolOBDData();
  public final static native void delete_DataPoolOBDData(long jarg1);
  public final static native void DataPoolOBDReadynessCode_i32CatalystState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_i32CatalystState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native void DataPoolOBDReadynessCode_i32HeatedCatalystState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_i32HeatedCatalystState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native void DataPoolOBDReadynessCode_i32EVAPSystemState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_i32EVAPSystemState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native void DataPoolOBDReadynessCode_i32SecondaryAirSystemState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_i32SecondaryAirSystemState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native void DataPoolOBDReadynessCode_i32OxygenSensorState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_i32OxygenSensorState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native void DataPoolOBDReadynessCode_i32OxygenSensorHeaterState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_i32OxygenSensorHeaterState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native void DataPoolOBDReadynessCode_I32EGRState_set(long jarg1, DataPoolOBDReadynessCode jarg1_, int jarg2);
  public final static native int DataPoolOBDReadynessCode_I32EGRState_get(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native long new_DataPoolOBDReadynessCode();
  public final static native void delete_DataPoolOBDReadynessCode(long jarg1);
  public final static native void DataPoolIMAState_i32FanState_set(long jarg1, DataPoolIMAState jarg1_, int jarg2);
  public final static native int DataPoolIMAState_i32FanState_get(long jarg1, DataPoolIMAState jarg1_);
  public final static native void DataPoolIMAState_bo_request_override_soc_set(long jarg1, DataPoolIMAState jarg1_, boolean jarg2);
  public final static native boolean DataPoolIMAState_bo_request_override_soc_get(long jarg1, DataPoolIMAState jarg1_);
  public final static native void DataPoolIMAState_u32_request_override_soc_new_value_set(long jarg1, DataPoolIMAState jarg1_, long jarg2);
  public final static native long DataPoolIMAState_u32_request_override_soc_new_value_get(long jarg1, DataPoolIMAState jarg1_);
  public final static native void DataPoolIMAState_bo_request_override_fan_state_set(long jarg1, DataPoolIMAState jarg1_, boolean jarg2);
  public final static native boolean DataPoolIMAState_bo_request_override_fan_state_get(long jarg1, DataPoolIMAState jarg1_);
  public final static native void DataPoolIMAState_u32_request_override_fan_state_value_set(long jarg1, DataPoolIMAState jarg1_, long jarg2);
  public final static native long DataPoolIMAState_u32_request_override_fan_state_value_get(long jarg1, DataPoolIMAState jarg1_);
  public final static native long new_DataPoolIMAState();
  public final static native void delete_DataPoolIMAState(long jarg1);
  public final static native void DataPoolOBDDTC_u32_dtc_code_set(long jarg1, DataPoolOBDDTC jarg1_, long jarg2);
  public final static native long DataPoolOBDDTC_u32_dtc_code_get(long jarg1, DataPoolOBDDTC jarg1_);
  public final static native long new_DataPoolOBDDTC();
  public final static native void delete_DataPoolOBDDTC(long jarg1);
  public final static native void DataPoolDisplayedElementData_u32_element_set(long jarg1, DataPoolDisplayedElementData jarg1_, long jarg2);
  public final static native long DataPoolDisplayedElementData_u32_element_get(long jarg1, DataPoolDisplayedElementData jarg1_);
  public final static native void DataPoolDisplayedElementData_u32_row_set(long jarg1, DataPoolDisplayedElementData jarg1_, long jarg2);
  public final static native long DataPoolDisplayedElementData_u32_row_get(long jarg1, DataPoolDisplayedElementData jarg1_);
  public final static native void DataPoolDisplayedElementData_u32_col_set(long jarg1, DataPoolDisplayedElementData jarg1_, long jarg2);
  public final static native long DataPoolDisplayedElementData_u32_col_get(long jarg1, DataPoolDisplayedElementData jarg1_);
  public final static native void DataPoolDisplayedElementData_u32_row_span_set(long jarg1, DataPoolDisplayedElementData jarg1_, long jarg2);
  public final static native long DataPoolDisplayedElementData_u32_row_span_get(long jarg1, DataPoolDisplayedElementData jarg1_);
  public final static native void DataPoolDisplayedElementData_u32_col_span_set(long jarg1, DataPoolDisplayedElementData jarg1_, long jarg2);
  public final static native long DataPoolDisplayedElementData_u32_col_span_get(long jarg1, DataPoolDisplayedElementData jarg1_);
  public final static native long new_DataPoolDisplayedElementData();
  public final static native void delete_DataPoolDisplayedElementData(long jarg1);
  public final static native long get_obd_data_array_element(int jarg1);
  public final static native void set_obd_data_array_element(int jarg1, long jarg2, DataPoolOBDData jarg2_);
  public final static native int get_obd_data_array_num_of_elements();
  public final static native long get_main_view_elements_of_interest_array_element(int jarg1);
  public final static native void set_main_view_elements_of_interest_array_element(int jarg1, long jarg2, DataPoolDisplayedElementData jarg2_);
  public final static native int get_main_view_elements_of_interest_array_size();
  public final static native int get_main_view_elements_of_interest_count();
  public final static native void set_main_view_elements_of_interest_count(int jarg1);
  public final static native void set_main_view_num_of_cols(int jarg1);
  public final static native int get_main_view_num_of_cols();
  public final static native void set_main_view_num_of_rows(int jarg1);
  public final static native int get_main_view_num_of_rows();
  public final static native boolean get_read_all_obd_values();
  public final static native int set_read_all_obd_values(boolean jarg1);
  public final static native long get_obd_readyness_code();
  public final static native void set_obd_readyness_code(long jarg1, DataPoolOBDReadynessCode jarg1_);
  public final static native long get_ima_state();
  public final static native void set_ima_state(long jarg1, DataPoolIMAState jarg1_);
  public final static native long get_obd_dtc_array_element(int jarg1);
  public final static native void set_obd_dtc_array_element(int jarg1, long jarg2, DataPoolOBDDTC jarg2_);
  public final static native int get_obd_dtc_array_num_of_elements();
  public final static native int get_obd_dtc_count();
  public final static native void set_obd_dtc_count(int jarg1);
}
