/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.texelography.hybridinsight.datapool;

public class DataPoolDisplayedElementData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataPoolDisplayedElementData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataPoolDisplayedElementData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        data_poolJNI.delete_DataPoolDisplayedElementData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setU32_element(long value) {
    data_poolJNI.DataPoolDisplayedElementData_u32_element_set(swigCPtr, this, value);
  }

  public long getU32_element() {
    return data_poolJNI.DataPoolDisplayedElementData_u32_element_get(swigCPtr, this);
  }

  public void setU32_row(long value) {
    data_poolJNI.DataPoolDisplayedElementData_u32_row_set(swigCPtr, this, value);
  }

  public long getU32_row() {
    return data_poolJNI.DataPoolDisplayedElementData_u32_row_get(swigCPtr, this);
  }

  public void setU32_col(long value) {
    data_poolJNI.DataPoolDisplayedElementData_u32_col_set(swigCPtr, this, value);
  }

  public long getU32_col() {
    return data_poolJNI.DataPoolDisplayedElementData_u32_col_get(swigCPtr, this);
  }

  public void setU32_row_span(long value) {
    data_poolJNI.DataPoolDisplayedElementData_u32_row_span_set(swigCPtr, this, value);
  }

  public long getU32_row_span() {
    return data_poolJNI.DataPoolDisplayedElementData_u32_row_span_get(swigCPtr, this);
  }

  public void setU32_col_span(long value) {
    data_poolJNI.DataPoolDisplayedElementData_u32_col_span_set(swigCPtr, this, value);
  }

  public long getU32_col_span() {
    return data_poolJNI.DataPoolDisplayedElementData_u32_col_span_get(swigCPtr, this);
  }

  public DataPoolDisplayedElementData() {
    this(data_poolJNI.new_DataPoolDisplayedElementData(), true);
  }

}
