/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.texelography.hybridinsight.datapool;

public class DataPoolOBDDTC {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataPoolOBDDTC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataPoolOBDDTC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        data_poolJNI.delete_DataPoolOBDDTC(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setU32_dtc_code(long value) {
    data_poolJNI.DataPoolOBDDTC_u32_dtc_code_set(swigCPtr, this, value);
  }

  public long getU32_dtc_code() {
    return data_poolJNI.DataPoolOBDDTC_u32_dtc_code_get(swigCPtr, this);
  }

  public DataPoolOBDDTC() {
    this(data_poolJNI.new_DataPoolOBDDTC(), true);
  }

}
