/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.texelography.hybridinsight.datapool;

public class DataPoolIMAState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataPoolIMAState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataPoolIMAState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        data_poolJNI.delete_DataPoolIMAState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI32FanState(int value) {
    data_poolJNI.DataPoolIMAState_i32FanState_set(swigCPtr, this, value);
  }

  public int getI32FanState() {
    return data_poolJNI.DataPoolIMAState_i32FanState_get(swigCPtr, this);
  }

  public void setBo_request_override_soc(boolean value) {
    data_poolJNI.DataPoolIMAState_bo_request_override_soc_set(swigCPtr, this, value);
  }

  public boolean getBo_request_override_soc() {
    return data_poolJNI.DataPoolIMAState_bo_request_override_soc_get(swigCPtr, this);
  }

  public void setU32_request_override_soc_new_value(long value) {
    data_poolJNI.DataPoolIMAState_u32_request_override_soc_new_value_set(swigCPtr, this, value);
  }

  public long getU32_request_override_soc_new_value() {
    return data_poolJNI.DataPoolIMAState_u32_request_override_soc_new_value_get(swigCPtr, this);
  }

  public void setBo_request_override_fan_state(boolean value) {
    data_poolJNI.DataPoolIMAState_bo_request_override_fan_state_set(swigCPtr, this, value);
  }

  public boolean getBo_request_override_fan_state() {
    return data_poolJNI.DataPoolIMAState_bo_request_override_fan_state_get(swigCPtr, this);
  }

  public void setU32_request_override_fan_state_value(long value) {
    data_poolJNI.DataPoolIMAState_u32_request_override_fan_state_value_set(swigCPtr, this, value);
  }

  public long getU32_request_override_fan_state_value() {
    return data_poolJNI.DataPoolIMAState_u32_request_override_fan_state_value_get(swigCPtr, this);
  }

  public DataPoolIMAState() {
    this(data_poolJNI.new_DataPoolIMAState(), true);
  }

}
