/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.texelography.hybridinsight.datapool;

public class DataPoolOBDData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DataPoolOBDData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataPoolOBDData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        data_poolJNI.delete_DataPoolOBDData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setI32_identifier(int value) {
    data_poolJNI.DataPoolOBDData_i32_identifier_set(swigCPtr, this, value);
  }

  public int getI32_identifier() {
    return data_poolJNI.DataPoolOBDData_i32_identifier_get(swigCPtr, this);
  }

  public void setF_min(float value) {
    data_poolJNI.DataPoolOBDData_f_min_set(swigCPtr, this, value);
  }

  public float getF_min() {
    return data_poolJNI.DataPoolOBDData_f_min_get(swigCPtr, this);
  }

  public void setF_max(float value) {
    data_poolJNI.DataPoolOBDData_f_max_set(swigCPtr, this, value);
  }

  public float getF_max() {
    return data_poolJNI.DataPoolOBDData_f_max_get(swigCPtr, this);
  }

  public void setF_zero(float value) {
    data_poolJNI.DataPoolOBDData_f_zero_set(swigCPtr, this, value);
  }

  public float getF_zero() {
    return data_poolJNI.DataPoolOBDData_f_zero_get(swigCPtr, this);
  }

  public void setF_value(float value) {
    data_poolJNI.DataPoolOBDData_f_value_set(swigCPtr, this, value);
  }

  public float getF_value() {
    return data_poolJNI.DataPoolOBDData_f_value_get(swigCPtr, this);
  }

  public void setStr_description(String value) {
    data_poolJNI.DataPoolOBDData_str_description_set(swigCPtr, this, value);
  }

  public String getStr_description() {
    return data_poolJNI.DataPoolOBDData_str_description_get(swigCPtr, this);
  }

  public void setStr_unit(String value) {
    data_poolJNI.DataPoolOBDData_str_unit_set(swigCPtr, this, value);
  }

  public String getStr_unit() {
    return data_poolJNI.DataPoolOBDData_str_unit_get(swigCPtr, this);
  }

  public DataPoolOBDData() {
    this(data_poolJNI.new_DataPoolOBDData(), true);
  }

}
